version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    ports:
      - '5435:5432'
    environment:
y      - POSTGRES_DB=todolist
      - POSTGRES_PASSWORD=admin
