version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - database
    volumes:
      - ./backend/.env:/app/.env
  database:
    image: postgres:14-alpine
    container_name: database
    restart: always
    ports:
      - '5435:5432'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_PASSWORD=admin
